Добавить время экспирации токена после refresh в nest-auth
steroids/nest-auth pull request #3
Opened 2024-09-25 06:43 UTC by alexpryazhnikov

Поправил ответ при обновлении access token'а: добавил туда время экспирации, так же как при /auth/login
Добавил успешный формат ответа в swagger
Изменил логику получения времени экспирации в сервисах - теперь оно извлекается из токена, а не генерируется отдельно

2024-09-25 15:12 UTC, vkoktashev approved these changes

2024-10-07 12:34 UTC, perlexed requested changes

2024-10-07 12:34 UTC, perlexed commented on src/infrastructure/services/SessionService.ts
> +        return null;
```suggestion
        const decodedToken = this.jwtService.decode(token) as { exp: number };
        return decodedToken && decodedToken.exp
            ? new Date(decodedToken.exp * 1000)
            : null;
```

2024-10-07 12:34 UTC, perlexed commented on src/domain/services/AuthLoginService.ts
>          return loginModel;
Я бы, раз эта функция меняется, поправил в ней флоу в более последовательный:

```ts
        const loginModelUid = generateUid();

        // Base sign options
        const baseTokenOptions = {
            issuer: ModuleHelper.getConfig<IAppModuleConfig>(AppModule).name,
            subject: String(user.id),
            jwtid: String(loginModelUid),
        };

        // Generate access token
        const accessToken = this.sessionService.signToken(tokenPayload, {
            ...baseTokenOptions,
            secret: ModuleHelper.getConfig<IAuthModuleConfig>(AuthModule).jwtAccessSecretKey,
            expiresIn: ModuleHelper.getConfig<IAuthModuleConfig>(AuthModule).accessTokenExpiresSec,
        });

        // Generate refresh token
        const refreshToken = this.sessionService.signToken(tokenPayload, {
            ...baseTokenOptions,
            secret: ModuleHelper.getConfig<IAuthModuleConfig>(AuthModule).jwtRefreshSecretKey,
            expiresIn: ModuleHelper.getConfig<IAuthModuleConfig>(AuthModule).refreshTokenExpiresSec,
        });

        const loginModel = DataMapper.create<AuthLoginModel>(AuthLoginModel, {
            uid: loginModelUid,
            userId: user.id,
            ipAddress: context.ipAddress,
            userAgent: context.userAgent,
            accessToken,
            accessExpireTime: this.sessionService.getTokenExpireTime(accessToken),
            refreshToken,
            refreshExpireTime: this.sessionService.getTokenExpireTime(refreshToken),
        });

        await this.repository.create(loginModel);

        return loginModel;
```

2024-10-10 07:47 UTC, perlexed commented on src/infrastructure/services/SessionService.ts
> +        return null;
@alexpryazhnikov обрати внимание, я еще константу переименовал - чтобы было не `decoded` (кто декодированный?) на `decodedToken`

2024-12-02 09:56 UTC, perlexed approved these changes

2024-12-04 05:54 UTC, merged